name: "tsql_utils_dbt_date_integration_tests"
version: "1.0"
config-version: 2

profile: "integration_tests"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ["tsql_utils", "dbt_utils"]
  - macro_namespace: dbt_date
    search_order:
      ["tsql_utils_dbt_date_integration_tests", "tsql_utils", "dbt_date"]

# TODO remove these variables in the next release
vars:
  "dbt_date:time_zone": "Pacific Standard Time"
  dbt_utils_dispatch_list: ["tsql_utils"]
  dbt_date_dispatch_list:
    ["tsql_utils", "tsql_utils_dbt_date_integration_tests"]

quoting:
  database: true
  identifier: true
  schema: true

models:
  dbt_date_integration_tests:
    +schema: dbt_date_integration_tests
    +materialized: table
    # needed bc of
    # https://github.com/calogica/dbt-date/pull/30
    # +enabled: false (THIS SHOULD WORK BUT DOESN'T!?)
    # test_dates:
    #   +enabled: true
    dates: &disabled
      +enabled: false
    dim_week: *disabled
    dim_date: *disabled
    dim_date_fiscal: *disabled
    dim_hour: *disabled
