
name: 'tsql_utils_dbt_expectations_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  'dbt_date:time_zone': 'Pacific Standard Time'
  dbt_utils_dispatch_list: ['tsql_utils']
  dbt_date_dispatch_list: ['tsql_utils']
  dbt_expectations_dispatch_list: ['tsql_utils']

models:
  dbt_expectations_integration_tests:
    schema_tests:
      data_test_factored:
        +materialized: table
      emails: &disabled #TODO
          +enabled: false 
      timeseries_data: *disabled
      # anders's weird NoneType error
      # (see https://github.com/calogica/dbt-expectations/pull/63)
      data_test: *disabled
      # # Need to implement for synapse
      # data_test: &not-synapse
      #     +enabled: "{{ target.name != 'synapse' }}" 
      data_test_factored: &not-synapse
          +enabled: "{{ target.name != 'synapse' }}" 