
name: 'tsql_utils_dbt_utils_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    
vars:
  dbt_utils_dispatch_list: ['tsql_utils']

models:
  dbt_utils_integration_tests:
    cross_db_utils:
      +enabled: true
    datetime:
      +enabled: true
    materializations:
      +enabled: false
    schema_tests:
      +enabled: false
    sql:
      +enabled: true
    web:
      +enabled: false

seeds:

  +quote_columns: false
  dbt_utils_integration_tests:

    cross_db:
      data_date_trunc:
        +column_types:
          updated_at: datetime
          day: date
          month: date

      data_dateadd:
        +column_types:
          from_time: datetime
          result: datetime

      data_datediff:
        +column_types:
          first_date: datetime
          second_date: datetime